quiz/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quizEngine.urls')),
]

quizEngine/urls.py
from django.urls import path
from . import views

app_name = 'quizEngine'

urlpatterns = [
    path('', views.welcome_view, name="welcome"),
    path('<slug:category>/',
         views.quiz_list,
         name='quiz_list'),
    path('<slug:category>/result/',
         views.quiz_save_result,
         name='quiz_save_result'),

]

quizEngine/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from ckeditor.fields import RichTextField
import re


class Category(models.Model):
    category_name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique=True)

    def __str__(self):
        return self.category_name

    def get_questions(self):
        return self.quiz_questions.all()

    class Meta:
        verbose_name_plural = 'Categories'


class Question(models.Model):
    category = models.ForeignKey(Category,
                                 related_name='quiz_questions',
                                 on_delete=models.CASCADE,
                                 default='')

    question = RichTextField(blank=True, null=True)
    num_of_answers = models.IntegerField(
        help_text="value should be from 1 to 4",
        validators=[MinValueValidator(1), 
                    MaxValueValidator(4)]
        )

    def __str__(self):
        return self.question_name()[:100] + "..."

    def question_name(self):
        question_pattern = re.compile('<.*?>|&([a-z0-9]+|#[0-9]{1,6}|#x[0-9a-f]{1,6});')
        question_text = re.sub(question_pattern, "", str(self.question))
        return question_text

    def get_answers(self):
        return self.answers.all()

    def correct_answers(self):
        answers = self.get_answers().filter(is_correct=True)
        return answers


class Answer(models.Model):
    question_key = models.ForeignKey(Question,
                                     related_name='answers',
                                     on_delete=models.CASCADE)
    answer_text = models.CharField(max_length=200)
    is_correct = models.BooleanField(default=False)

quizEngine/views.py
from django.urls.base import reverse
from quiz.services import QuizResultService
from quiz.dto import AnswerDTO, AnswersDTO, QuestionDTO, QuizDTO, ChoiceDTO
from django.core import paginator
from django.shortcuts import redirect, render
from django.http import JsonResponse
from .models import Answer, Question, Category
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def quiz_list(request, category):
    category_id = Category.objects.filter(slug=category)[0]
    questions = Question.objects.filter(category=category_id)
    paginator = Paginator(questions, 1)
    page = request.GET.get('question')
    try:
        questions = paginator.page(page)
    except PageNotAnInteger:
        questions = paginator.page(1)
    except EmptyPage:
        questions = paginator.page(paginator.num_pages)

    return render(request, 
                 'quiz/question/question.html',
                 context={'questions': questions,
                          'category': category_id})


def welcome_view(request):
    categories = Category.objects.all()
    return render(request, 'quiz/welcome.html',
                  context={'categories': categories})


def quiz_save_result(request, *args, **kwargs):
    import re
    result = 0
    if request.is_ajax():
        data = dict(request.POST.lists())

        data.pop('csrfmiddlewaretoken')
        category = data.pop('url')[0]

        category_id = Category.objects.filter(slug=category)[0]

        questions = Question.objects.filter(category=category_id)
        temp_data = {}
        for i in data.keys():
            t = re.findall('[0-9]+', i)[0]
            temp_data[t] = data[i]
             
        questions_data = []
        temp_answers = []
        display_correct_answers = []
        display_user_answers = []
        for i in questions:

            user_choice = []
            choices = []

            all_choices = i.get_answers()
            temp_correct_ans = []
            for j in all_choices:
                if j.is_correct:
                    temp_correct_ans.append(j.answer_text)
                ch = ChoiceDTO(str(j.pk), j.answer_text, j.is_correct)

                choices.append(ch)
            display_correct_answers.append(temp_correct_ans)
            temp_user_choice = []
            if str(i.pk) in temp_data.keys():
                for user_ch in temp_data[str(i.pk)]:
                    for choice in choices:
                        if choice.text == user_ch:
                            temp_user_choice.append(choice.text)
                            user_choice.append(choice.uuid)
            
            display_user_answers.append(temp_user_choice)
            answers = AnswerDTO(str(i.pk), user_choice)
            temp = QuestionDTO(str(i.pk), i.question, choices)
            temp_answers.append(answers)
            questions_data.append(temp)

        answers_data = AnswersDTO(str(category_id), temp_answers)
        quiz_data = QuizDTO(str(category_id), category.title(), questions_data)

        calculation = QuizResultService(quiz_data, answers_data)
        result = calculation.get_result()
        result = round(result, 2)
        display_data = zip(questions, display_correct_answers, display_user_answers)
        return render(request, 'quiz/result/results.html',
                      context={"result": result * 100,
                               "questions": display_data,
                               'category': category_id})
    return redirect('quizEngine:welcome')

quizEngine/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/quiz.css' %}">
    <script src="{% static 'js/quiz.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@2.2.1/src/js.cookie.min.js"></script>
</head>
<body>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

quizEngine/templates/paginator.html
<style>
.pagination {
  display: inline-flex;
  max-width: 100%;
}
.pagination > a {
  max-width: 100%;
}

.pagination a {

  color: white;
  float: left;

  padding: 8px 8px;
  text-decoration: none;
}

li{
  list-style: none;
}
li:hover, .paginator-span:hover{
    background: #c0b9b0;
    -webkit-box-shadow: 2px 2px 2px 0 rgba(0,0,0,0.3) ;
    box-shadow: 2px 2px 2px 0 rgba(0,0,0,0.3) ;
    -webkit-transition: all 200ms cubic-bezier(0.42, 0, 0.58, 1);
    -moz-transition: all 200ms cubic-bezier(0.42, 0, 0.58, 1);
    -o-transition: all 200ms cubic-bezier(0.42, 0, 0.58, 1);
    transition: all 200ms cubic-bezier(0.42, 0, 0.58, 1);
}

.paginator-span{
  display: inline-block;
    max-width: 100%;
    padding: 10px 20px;
    -webkit-border-radius: 3px;
    border-radius: 3px;
    font: normal normal 20px "Trebuchet MS", Helvetica, sans-serif;
    color: rgba(255,255,255,0.9);
    -o-text-overflow: clip;
    text-overflow: clip;
    background: #9a938a;
    -webkit-box-shadow: 2px 2px 2px 0 rgba(0,0,0,0.2) ;
    box-shadow: 2px 2px 2px 0 rgba(0,0,0,0.2) ;
    text-shadow: -1px -1px 0 rgba(15,73,168,0.66) ;
    -webkit-transition: all 300ms cubic-bezier(0.42, 0, 0.58, 1);
    -moz-transition: all 300ms cubic-bezier(0.42, 0, 0.58, 1);
    -o-transition: all 300ms cubic-bezier(0.42, 0, 0.58, 1);
    transition: all 300ms cubic-bezier(0.42, 0, 0.58, 1);
  padding: 10px;

  letter-spacing: 0;
  font-size: 20px;
}

</style>
<div class="pagination" style="margin-left: auto; margin-right: auto;">
    {% if page.has_previous %}
    <a href="?question={{ page.previous_page_number }}">
    <span class="paginator-span">← Предыдущий вопрос</span>
    </a>
    {% endif %}
    {% if page.has_next %}
    <a href="?question={{ page.next_page_number }}">
      <span class="paginator-span">Следующий вопрос →</span>
    </a>
    {% endif %}
    </span>
</div>

quizEngine/templates/quiz/question/question.html
{% extends "base.html" %}
{% load static %}
{% load category_templates %}
{% block title %}

{{ category.category_name }}
{% endblock %}

{% block content %}
<div class="question">
    <h1>Викторина {{ category.category_name }}</h1>
    {% if not questions %}
        <h3>Sorry, there are no questions on this topic yet</h3>
        <p>Would you like to return and try another quiz?</p>
        <a href="{% url 'quizEngine:welcome' %}" class="link-button">Back to quizes!</a>
    {% else %}
    {% for q in questions %}
    <form class="question-form">
        <div class="all-answers">
           {% csrf_token %}
        <p>Вопрос {{ category|get_question_index:q }} из {{ category.get_questions|length }}</p>
        <div class="question-text">{{ q.question|safe }}</div>
        {% if q.correct_answers.count > 1 %}
        <div class="answers-container">
            <p>Выберите несколько вариантов ответа</p>
           {% for a in q.get_answers %}
                            
                <label for="answer-input" class="answer">
                    <input type="checkbox" class="answer-input" 
                    name="question{{ q.pk }}" 
                    value="{{ a.answer_text }}">
                    <span>{{ a.answer_text }}</span>
                </label>               
            {% endfor %} 
        </div>
            
        {% else %}
        <div class="answers-container">
            <p>Выберите один вариант ответа</p>
            {% for a in q.get_answers %}
            <label for="answer-input" class="answer">
                     <input type="radio" class="answer-input" 
                name="question{{ q.pk }}"
                value="{{ a.answer_text }}">
                <span>{{ a.answer_text }}</span>
            </label>              
                
            {% endfor %}
        </div>
            
        {% endif %} 
        </div>
        
    </form>
    
    {% endfor %}
{% include 'paginator.html' with page=questions %}

</div>
<button type="submit" class="submit_btn">Завершить викторину!</button>

{% endif %}
{% endblock %}

quizEngine/templates/quiz/result/results.html
{% extends "base.html" %}
{% load static %}

{% block title %}

Результаты викторины {{ category.category_name }}
{% endblock %}
{% block content %}
<h1 class="result-title">Результаты викторины</h1>
<p class="result-percentage">
    Вы ответили верно на {{ result }}%  вопросов
</p>

<div class="quiz-result">
    {% for q in questions %}
        <div class="question-txt">{{ q.0.question|safe }}</div>
        <div class="correct-answer">
          <h5>Правильный ответ:</h5>
            {% for corr_ans in q.1 %}
                <p>{{ corr_ans }}</p>
            {% endfor %}  
        </div>
        
        <div class="user-answer">
            <h5>Ваш ответ:</h5>
            {% if not q.2 %}
                <p class="not-answered">Вы не ответили на этот вопрос :(</p>
            {% else %}
                {% for user_ans in q.2 %}
                    <p class="usr-ans">{{ user_ans }}</p>
                {% endfor %}
            {% endif %}
        </div>
            
    {% endfor %}
<a href="{% url 'quizEngine:quiz_list' category.slug %}" class="link-button">Попробовать снова!</a>
<a href="{% url 'quizEngine:welcome' %}" class="link-button">Главная</a>
</div>

{% endblock %}

quizEngine/templates/quiz/welcome.html
{% extends "base.html" %}

{% block title %}
Викторина
{% endblock %}
{% block content %}

<h1>Добро пожаловать на викторину!</h1>

<div class="categories">
    <h3 class="choose-category-label">Выберите категорию викторины</h3>
    
    <ul class="categories-list">
        {% for c in categories %}
        <li>
            <a href="{% url 'quizEngine:quiz_list' c.slug %}" 
        class="link-button">{{ c.category_name }}</a>
        </li>
        {% endfor %}
    </ul>
    
    
</div>
<p>
    
</p>

{% endblock %}